eureka:
  client:
    healthcheck:
      enabled: true

server:
  port: 9010

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_app
    username: root
    password: password
    initialization-mode: always
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: none